### ISSUE TITLE
Create Front End Design for Chrome Extension

### ISSUE THREAD

**Issue by SamarKaranch** [StudentJamesChen/AidUI#2]
Related User Story: #1 

This task involves creating a design using Figma for the front end of the AID-UI Chrome extension.

Estimated Effort: This task will require minimal effort because we have to create a front end for a button and an image viewer.

Dependencies: None

Initial Assignments: Front-End Developer

Milestone: Sprint 1

Acceptance Criteria: The design must include a button and an image viewer. The design must also be accessible and easy to navigate and use.

**Comment by StudentJamesChen** [comment]
Pivoted away from this user story, please refer to #1 if needed.

We did create a basic Figma mockup of the Chrome Extension though.
