### ISSUE TITLE
Create Front End Infrastructure for Dark Pattern Scanning

### ISSUE THREAD

**Issue by SamarKaranch** [StudentJamesChen/AidUI#3]
Related User Story: #1 

This task involves adding a button to the front end. This button will submit an image that will be fed to the AID-UI program. The output from AID-UI will also be displayed on the front end.

Estimated Effort: This will require a moderate amount of effort. The AID-UI program itself is already built so we have to link our front end to AID-UI so that it takes in the image. 

Dependencies: #2 

Initial Assignments: Front-End Developer

Milestone: Sprint 1

Acceptance Criteria: The front end is built where a user will be able to submit an image to AID-UI and the response will be displayed.

**Comment by StudentJamesChen** [comment]
Pivoted from this user story, please refer to #1.
