### ISSUE TITLE
Publish AidUI

### ISSUE THREAD

**Issue by SamarKaranch** [StudentJamesChen/AidUI#4]
Related User Story: #1
This task involves making AID-UI be available on the Chrome web store.
 
Estimated Effort: This will be a significant amount of effort because we would have to make sure AID-UI can run on other computers and we would have to go through the process of publishing onto the Chrome web store.

Dependencies: #2 and #3

Initial Assignments: Entire Team

Milestone: Sprint 2, stretch goal

Acceptance Criteria: AID-UI will be available for download on the Chrome web store and work properly.

**Comment by StudentJamesChen** [comment]
Pivoted from this user story, please refer to #1.
